#pragma once

//#include "kengine/systems/animation.hpp"
#include "kengine/systems/character_animation.hpp"
#include "kengine/systems/color.hpp"
//#include "kengine/systems/fog.hpp"
#include "kengine/systems/movement.hpp"
#include "kengine/systems/npc.hpp"
// #include "kengine/systems/particle.hpp"
#include "kengine/systems/physics.hpp"
//#include "kengine/systems/player.hpp"
//#include "kengine/systems/render.hpp"
#include "kengine/systems/scroll.hpp"
#include "kengine/systems/speech.hpp"
#include "kengine/systems/text.hpp"
#include "kengine/systems/tile.hpp"
#include "kengine/systems/tiled_scroll.hpp"
#include "kengine/systems/timer.hpp"
//#include "kengine/systems/transform.hpp"
